sudo: false
language: ruby
rvm: 2.2.5
branches:
  only:
    - master
script:
  - "bundle install --full-index"
  - "bundle exec rake build"
deploy:
  provider: pages
  skip_cleanup: false
  github_token: $GITHUB_API_KEY # Set in travis-ci.org dashboard
  local_dir: _site
  repo: psadmin-io/psadmin-io.github.io
  fqdn: wiki.psadmin.io
  target_branch: master
  on:
    branch: master
env:
  matrix:
  - secure: tvcaQhFGRUw9IZ8EAHYuKfEo6bLRObxXcI91AS53SvFscy/De4Tn2wH/aeeeoHOVnvHHA+HXeIOJu1gKQxFocxk6kiajgNmUjlZVWXTpprftMSsodgLY/Je22J3h6hvmabJD9jLzaIvxws0hIcHV712yedXSRLCGM3ldHzLfn619qdbI4yRoxiOjJ3j1tveCDPgyy5at++nt2SyN/cuVw2v7ljSwZIBCQJrz03b/KBfKrn6mVBB2mUxhEQhf7yp+g/lUOF8A/+AbvlrynPT1ZWzfkfZDCVJIsZOG6sw4KfxGA37CAsLUlISnKyFVvhMhAMxSzD0Tt8zlCDo0lQZOTC1t1nlRaTrwEsJ+psLaZkgUvBKQBG/SxS0qGeGycyDV8tJtxCSDOhHezRz5c7whGQMEtvg9Tb9ufCPGnL6JQMb3/SZ9XuiXqjTHUUVQMWPGYDMT61V58GjEGiEC81WVAwg8I9KBfVQPdz2MCtD8VzmvavP9syGUEVxpioRWZU+QGGhCaBKEQSXAM13lt/lKDdQL33A9WBhm7Dt9i8/IChP8OQ/wtiBp6f3VkB4/xx/fL/u3FuhiPhqbrAqTCkEiPjzcUM9jSDMC77k17xg4BPzfinqbn+893YG6vSge/o2TsGfom4GR0CHDVGFcZBz+X26hrZFnaWU5mwC6Snb/SHg=
